apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.image.port | default 80 }}
  selector:
    app: my-app