apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
  labels:
    app: my-nginx-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.nodePort | default 30080 }}
  type: NodePort
  selector:
    app: my-nginx-app