- name: Create VMs for Kubernetes cluster
  ngine_io.cloudstack.cs_instance:
    name: "{{ item.name }}"
    template: "{{ vm_template }}"
    hypervisor: VMware
    zone: "{{ k8s_zone }}"
    service_offering: "{{ vm_service_offering }}"
    disk_offering: "{{ vm_disk_offering }}"
    networks: 
      - "{{ k8s_network_name }}"
  loop:
    - { name: "k8s-control-node" }
    - { name: "k8s-node" }