- name: Create a CloudStack VM
  hosts: localhost
  gather_facts: false
  module_defaults:
    group/ngine_io.cloudstack.cloudstack:
      api_key: "{{ cloudstack_api_key }}"
      api_secret: "{{ cloudstack_api_secret }}"
      api_url: "{{ cloudstack_api_url }}"
  tasks:
    - name: Create VM using cloudstack_vm role
      include_role:
        name: cloudstack_vm
        tasks_from: create_vm.yml
      vars:
        vm_name: "{{ k8s_autoscale_worker }}"
        inventory_name: "worker"
        inventory_group: "workers"
        vm_ip: "{{ k8s_allocated_ip }}"
        vm_ssh_port: "{{ k8s_worker_ssh_port }}"
        vm_service_offering: "{{ vm_worker_service_offering }}"
        vm_network_name: "{{ k8s_network_name }}"

- name: Set up the VM for Kubernetes
  hosts: workers
  become: true
  roles:
    - k8s_node_setup

- name: Generate join command on the master
  hosts: masters
  become: true
  tasks:
    - name: Run command task from k8s_control_node role
      import_role:
        name: k8s_control_node
        tasks_from: command.yml

- name: Join worker nodes to the Kubernetes cluster
  hosts: workers
  become: true
  roles:
    - k8s_worker_node
