# In this version, the infra is handled by Terraform so we only need to set up the k8s cluster.

- name: Setup nodes for k8s
  hosts: all
  become: true
  roles:
    - k8s_node_setup

- name: Setup k8s on control node
  hosts: masters
  become: true
  roles:
    - k8s_control_node

- name: Setup cloudstack CCM
  hosts: masters
  vars_files:
    - vault.yml  
  roles:
    - cloudstack_ccm

- name: Add worker nodes to cluster
  hosts: workers
  become: true
  roles:
    - k8s_join
