- name: Create an isolated network for Kubernetes
  module_defaults:
    group/ngine_io.cloudstack.cloudstack:
      api_key: "{{ cloudstack_api_key }}"
      api_secret: "{{ cloudstack_api_secret }}"
      api_url: "{{ cloudstack_api_url }}"
  block:
    - name: Create a network
      ngine_io.cloudstack.cs_network:
        name: "{{ network_name }}"
        zone: "{{ vm_zone }}"
        network_offering: "{{ network_offering }}"
      register: network_result
    - name: Allocate an IP address
      ngine_io.cloudstack.cs_ip_address:
        zone: "{{ vm_zone }}"
        network: "{{ network_name }}"
      register: allocated_ip
    - name: Print ip address
      debug:
        msg: "Allocated IP address: {{ allocated_ip.ip_address }}"
    - name: Create a firewall rule for the IP address
      ngine_io.cloudstack.cs_firewall:
        zone: "{{ vm_zone }}"
        ip_address: "{{ allocated_ip.ip_address }}"
        protocol: tcp
        start_port: 80
        end_port: 80
        cidr: 0.0.0.0/0
    - name: Set network facts for other roles
      set_fact:
        k8s_network_id: "{{ network_result.id }}"
        k8s_network_name: "{{ network_name }}"
        k8s_allocated_ip: "{{ allocated_ip.ip_address }}"
