- name: Add ssh access for the control and worker nodes
  ngine_io.cloudstack.cs_portforward:
    ip_address: "{{ k8s_allocated_ip }}"
    zone: "{{ k8s_zone }}"
    vm: "{{ item.name }}"
    public_port: "{{ item.ssh_port }}"
    private_port: 22
  loop:
   - { name: "{{ k8s_control_node }}", ssh_port: "{{ k8s_control_node_ssh_port }}" }
   - { name: "{{ k8s_node }}", ssh_port: "{{ k8s_worker_node_ssh_port }}" }


- name: Add load balancer rule for the api server
  ngine_io.cloudstack.cs_loadbalancer_rule:
    name: k8s-api-lb-rule
    public_ip: "{{ k8s_allocated_ip }}"
    public_port: 6443
    private_port: 6443
    algorithm: roundrobin

- name: add control node to load balancer
  ngine_io.cloudstack.cs_loadbalancer_rule_member:
    name: k8s-api-lb-rule
    vms: "{{ k8s_control_node }}"
