- name: Add ssh access for control node
  include_tasks: ssh_access.yml
  vars:
    vm_name: "{{ k8s_control_node }}"
    vm_ip: "{{ k8s_allocated_ip }}"
    vm_zone: "{{ k8s_zone }}"
    vm_ssh_port: "{{ k8s_control_node_ssh_port }}"

- name: Add ssh access for worker nodes
  include_tasks: ssh_access.yml
  vars:
    vm_name: "{{ k8s_node }}-{{ item }}"
    vm_ip: "{{ k8s_allocated_ip }}"
    vm_zone: "{{ k8s_zone }}"
    vm_ssh_port: "{{ (k8s_control_node_ssh_port | int) + (item | int) }}"
  loop: "{{ range(1, worker_count + 1) | list }}"
  loop_control:
    label: "{{ k8s_node }}-{{ item }}"

- name: Add load balancer rule for the api server
  ngine_io.cloudstack.cs_loadbalancer_rule:
    name: k8s-api-lb-rule
    public_ip: "{{ k8s_allocated_ip }}"
    public_port: 6443
    private_port: 6443
    algorithm: roundrobin

- name: Add control node to load balancer
  ngine_io.cloudstack.cs_loadbalancer_rule_member:
    name: k8s-api-lb-rule
    ip_address: "{{ k8s_allocated_ip }}"
    vms: "{{ k8s_control_node }}"
