name: Deploy to Kubernetes
on:
  push:
    branches: [ master ]

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Initialize Go modules
      run: |
        cd server
        go mod init myserver
        go mod tidy

    - name: Install dependencies
      run: |
        cd server
        go mod download

    - name: Run tests
      run: |
        cd server
        go test
        
    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: fs
        scan-ref: ./server
        severity: CRITICAL,HIGH
        ignore-unfixed: true

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: fancyvanilla/kube-dev:v1
        context: "{{defaultContext}}:server"

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set kubeconfig from secret
      env:
        KUBECONFIG_CONTENT: ${{ secrets.KUBECONFIG_CONTENT }}
      run: |
        $env:KUBECONFIG_CONTENT | Out-File -FilePath kubeconfig -Encoding utf8
        echo "KUBECONFIG=$PWD/kubeconfig" >> $env:GITHUB_ENV
      shell: powershell

    - name: Helm lint
      run: helm lint ./helm

    - name: Deploy app
      run: |
        helm upgrade --install myapp ./helm
